export type PetalZone = "bg" | "mid" | "fg";

export type PetalDef = {
  id: string;
  src: string;
  h: number;
  w: number;
  zone: PetalZone;
  left: number;
  top: number;
  s: number;
  o: number;
  blur: number;
  rot: number;
  depth: number;
  m?: boolean;
  t?: boolean;
};

/** Petal definitions from `petalDefs()` in handoff/Florea Hero.dc.html — verbatim. */
export function petalDefs(): PetalDef[] {
  return [
    {
      id: "b1",
      src: "/hero/petal_02.png",
      h: 44,
      w: 39,
      zone: "bg",
      left: 31,
      top: 24,
      s: 0.6,
      o: 0.5,
      blur: 0.6,
      rot: 30,
      depth: 3,
      m: true,
    },
    {
      id: "b2",
      src: "/hero/petal_05.png",
      h: 39,
      w: 41,
      zone: "bg",
      left: 56,
      top: 80,
      s: 0.55,
      o: 0.45,
      blur: 1,
      rot: -40,
      depth: 2.5,
    },
    {
      id: "b3",
      src: "/hero/petal_08.png",
      h: 45,
      w: 57,
      zone: "bg",
      left: 71,
      top: 19,
      s: 0.7,
      o: 0.6,
      blur: 0.4,
      rot: 12,
      depth: 3.5,
    },
    {
      id: "b4",
      src: "/hero/petal_09.png",
      h: 48,
      w: 52,
      zone: "bg",
      left: 43,
      top: 61,
      s: 0.5,
      o: 0.5,
      blur: 0.8,
      rot: -15,
      depth: 2.5,
    },
    {
      id: "m1",
      src: "/hero/petal_01.png",
      h: 67,
      w: 58,
      zone: "mid",
      left: 45,
      top: 12,
      s: 1.1,
      o: 0.95,
      blur: 0,
      rot: -12,
      depth: 14,
      m: true,
    },
    {
      id: "m2",
      src: "/hero/petal_04.png",
      h: 65,
      w: 55,
      zone: "mid",
      left: 76,
      top: 7,
      s: 1.25,
      o: 1,
      blur: 0,
      rot: 18,
      depth: 16,
      m: true,
    },
    {
      id: "m3",
      src: "/hero/petal_07.png",
      h: 60,
      w: 64,
      zone: "mid",
      left: 34,
      top: 65,
      s: 1.15,
      o: 0.95,
      blur: 0,
      rot: -30,
      depth: 17,
      m: true,
    },
    {
      id: "m4",
      src: "/hero/petal_08.png",
      h: 45,
      w: 57,
      zone: "mid",
      left: 51,
      top: 74,
      s: 1.0,
      o: 0.9,
      blur: 0,
      rot: 40,
      depth: 13,
    },
    {
      id: "m5",
      src: "/hero/petal_09.png",
      h: 48,
      w: 52,
      zone: "mid",
      left: 85,
      top: 30,
      s: 1.0,
      o: 0.9,
      blur: 0,
      rot: -5,
      depth: 15,
    },
    {
      id: "m6",
      src: "/hero/petal_05.png",
      h: 39,
      w: 41,
      zone: "mid",
      left: 29,
      top: 47,
      s: 0.9,
      o: 0.8,
      blur: 0,
      rot: 60,
      depth: 12,
    },
    {
      id: "m7",
      src: "/hero/petal_03_large.png",
      h: 114,
      w: 97,
      zone: "mid",
      left: 73,
      top: 86,
      s: 0.85,
      o: 0.9,
      blur: 0,
      rot: 25,
      depth: 18,
    },
    {
      id: "f1",
      src: "/hero/petal_03_large.png",
      h: 114,
      w: 97,
      zone: "fg",
      left: -5,
      top: 56,
      s: 2.6,
      o: 0.7,
      blur: 6,
      rot: 20,
      depth: 26,
    },
    {
      id: "f2",
      src: "/hero/petal_06_large.png",
      h: 105,
      w: 87,
      zone: "fg",
      left: 55,
      top: 76,
      s: 2.8,
      o: 0.75,
      blur: 5,
      rot: -35,
      depth: 30,
      m: true,
    },
    {
      id: "f3",
      src: "/hero/petal_06_large.png",
      h: 105,
      w: 87,
      zone: "fg",
      left: 91,
      top: 58,
      s: 2.2,
      o: 0.65,
      blur: 5,
      rot: 15,
      depth: 24,
    },
    {
      id: "f4",
      src: "/hero/petal_03_large.png",
      h: 114,
      w: 97,
      zone: "fg",
      left: 86,
      top: 88,
      s: 2.0,
      o: 0.6,
      blur: 4,
      rot: -60,
      depth: 22,
      t: false,
    },
    {
      id: "f5",
      src: "/hero/petal_06_large.png",
      h: 105,
      w: 87,
      zone: "fg",
      left: 6,
      top: 90,
      s: 1.8,
      o: 0.55,
      blur: 7,
      rot: 70,
      depth: 28,
      t: false,
    },
  ];
}
